### ISSUE TITLE
Android/Quest Support

### ISSUE THREAD

**Issue by GiantSox** [marek-simonik/record3d_offline_unity_demo#5]
Hi there,

I'd like to be able to run this on Android -- would it be possible to get an android version of the native library, or sources so I can compile it myself? (ideally with a CMakeLists to make it easy :) )

**Comment by marek-simonik** [comment]
Hi, yes, the source code for the library can be downloaded [here](https://record3d.app/record3d_unity_playback.zip).

**Comment by TheWiselyBearded** [comment]
Hey, @GiantSox, if you haven't gotten around to recompiling the program on Android, I went ahead and did as well for my own purposes. The `.so` is located in the build directory of the zip. Thank you @marek-simonik for sharing the src.
[record3d_unity_playback-android.zip](https://github.com/marek-simonik/record3d_offline_unity_demo/files/13243463/record3d_unity_playback-android.zip)
